# Generated by Django 4.1.3 on 2022-12-10 11:06

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('dateTime', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=1)),
                ('Status', models.CharField(max_length=1)),
                ('Priority', models.CharField(max_length=1)),
                ('Source', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('QueueNumber', models.IntegerField(unique=True)),
                ('Action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Action', to='ActionsApplication.actions')),
            ],
        ),
    ]
